# This is a TOML-format file. For the spec, see https://github.com/toml-lang/toml#spec

# URL to the database
db_url = 'postgresql://postgres:anypasswordworkslocally@localhost/anitya'

# List of admins based on their openid
# anitya_web_admins = ["http://pingou.id.fedoraproject.org/"]

# A set of booleans to enable or disable OpenID providers
anitya_web_fedora_openid = "https://id.fedoraproject.org"
anitya_web_allow_fas_openid = true
anitya_web_allow_google_openid = true
anitya_web_allow_yahoo_openid = true
anitya_web_allow_generic_openid = true

blacklisted_users = []

# The logging configuration, in dictConfig format.
[anitya_log_config]
    version = 1
    disable_existing_loggers = false

    [anitya_log_config.formatters]
        [anitya_log_config.formatters.simple]
            format = "[%(name)s %(levelname)s] %(message)s"

    [anitya_log_config.handlers]
        [anitya_log_config.handlers.console]
            class = "logging.StreamHandler"
            formatter = "simple"
            stream = "ext://sys.stdout"

    [anitya_log_config.loggers]
        [anitya_log_config.loggers.anitya]
            level = "INFO"
            propagate = false
            handlers = ["console"]

    [anitya_log_config.root]
        level = "INFO"
        handlers = ["console"]
